trigger:
- main

variables:
  imageName: 'cshailesh/test_2025/test_01'
  dockerHubUsername: 'cshailesh'
  dockerHubPassword: $(dockerHubPassword)  # Define this securely in pipeline variables

stages:
- stage: BuildAndPush
  jobs:
  - job: DockerJob
    pool:
      name: Testing_Agent

    steps:
    - checkout: self

    - script: |
        echo "$(dockerHubPassword)" | docker login -u "$(dockerHubUsername)" --password-stdin
      displayName: 'Docker Login'

    - script: |
        docker build -t $(imageName):latest .
      displayName: 'Docker Build'

    - script: |
        docker push $(imageName):latest
      displayName: 'Docker Push'
