trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'cshailesh/test_2025'  # Docker Hub repo name
  tag: '$(Build.BuildId)'                                         # Use build ID as tag (optional)

steps:
- task: Checkout@1
  displayName: 'Checkout source code'

- task: Docker@2
  displayName: 'Login to Docker Hub'
  inputs:
    command: login
    containerRegistry: 'Docker_hub'  # your Docker Hub service connection name

- task: Docker@2
  displayName: 'Build and push Docker image'
  inputs:
    command: buildAndPush
    repository: $(imageName)
    dockerfile: '**/Dockerfile'
    containerRegistry: 'Docker_hub'
    tags: |
      $(tag)
      latest  # optionally push latest tag too
