trigger:
- main

variables:
  imageName: 'cshailesh/test_2025/test_01'

stages:
- stage: BuildAndPush
  jobs:
  - job: DockerJob
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self

    - task: Docker@2
      displayName: 'Build and Push to Docker Hub'
      inputs:
        containerRegistry: 'Docker_hub'  # Must match the service connection name exactly
        repository: '$(imageName)'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          latest
          $(Build.BuildId)
